In [1]:
import pandas as pd

In [2]:
trial_df = pd.read_csv("/home/bily/python/activity_tracker/data/Recovery workout log - barbell weights.csv")

In [3]:
trial_df.head()

,date,exercise,reps,set,mass (lbs),mass (kgs),rest,notes,to failure?
0,25.8.15,calf raise machine,10,3,0,0.0,60.0,60/40 2 legged,yes
1,25.8.15,heel raise squat bar,10,3,0,0.0,60.0,NaN,yes
2,25.8.15,1 leg extension,10,3,45,20.0,60.0,NaN,yes
3,25.8.15,1 leg curl,10,3,30,14.0,60.0,NaN,yes
4,25.8.22,calf raise machine,10,3,0,0.0,60.0,70/30 2 legged,yes

In [4]:
trial_df.loc[trial_df['exercise'].str.contains("dead"), 'mass (lbs)'].max()

253

In [5]:
index = trial_df[trial_df['date'].str.count('\.') == 1].index
index

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_8291/1560749460.py:1: SyntaxWarning: invalid escape sequence '\.'
  index = trial_df[trial_df['date'].str.count('\.') == 1].index

Index([167, 170, 171, 172], dtype='int64')

In [6]:
a = "24.03.24"
print(a.replace(".", ''))

240324

In [7]:
def fix_date(value):
    fresh_start = value.replace(".", "").strip().replace(" ", "")
    if len(fresh_start) == 6:
        new_value = fresh_start[0:2] + "." + fresh_start[2:4] + "." + fresh_start[4:6]
    elif len(fresh_start) == 5:
        if fresh_start[0:3] == "258":
            new_value = fresh_start[0:2] + ".0" + fresh_start[2:3] + "." + fresh_start[3:5]
    else:
        new_value = "bugger"
    return new_value

trial_df['date'] = trial_df['date'].apply(fix_date)

In [8]:
trial_df.head()

,date,exercise,reps,set,mass (lbs),mass (kgs),rest,notes,to failure?
0,25.08.15,calf raise machine,10,3,0,0.0,60.0,60/40 2 legged,yes
1,25.08.15,heel raise squat bar,10,3,0,0.0,60.0,NaN,yes
2,25.08.15,1 leg extension,10,3,45,20.0,60.0,NaN,yes
3,25.08.15,1 leg curl,10,3,30,14.0,60.0,NaN,yes
4,25.08.22,calf raise machine,10,3,0,0.0,60.0,70/30 2 legged,yes

In [9]:
trial_df['date'] = pd.to_datetime(trial_df['date'], format='%y.%m.%d')

In [10]:
trial_df.head()

,date,exercise,reps,set,mass (lbs),mass (kgs),rest,notes,to failure?
0,2025-08-15,calf raise machine,10,3,0,0.0,60.0,60/40 2 legged,yes
1,2025-08-15,heel raise squat bar,10,3,0,0.0,60.0,NaN,yes
2,2025-08-15,1 leg extension,10,3,45,20.0,60.0,NaN,yes
3,2025-08-15,1 leg curl,10,3,30,14.0,60.0,NaN,yes
4,2025-08-22,calf raise machine,10,3,0,0.0,60.0,70/30 2 legged,yes